development:
  adapter: postgresql
  encoding: unicode
  database: todolist_development
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: todolist_test
  pool: 5
  host: localhost
  username: action
  password: